#!/bin/sh
home_dir="$PWD";

rm -rf dist &&
tsc --project . --target esnext --module es2015 --outDir dist/modules --declaration --declarationDir dist/types &&
tsc --project . --target es2015 --lib esnext --downlevelIteration --module amd --outDir dist/amd &&
tsc --project . --target es2015 --lib esnext --downlevelIteration --module commonjs --outDir dist/commonjs &&

mkdir -p dist/commonjs/node_modules &&
ln -s $home_dir/dist/commonjs/src/ dist/commonjs/node_modules/no-show
